databases:
  - name: jaspo-regimen-db
    plan: free
    databaseName: jaspo_regimen_master_production
    user: jaspo_regimen

services:
  - type: web
    name: jaspo-regimen-master
    runtime: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jaspo-regimen-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
